### ISSUE TITLE
Autoinsurance auto-rebuy allows ships to exceed their Bat/Bot limits

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#27]
After buying a Cruiser and turning on autoinsurance (all), I later noticed I was still getting the 4/2 batteries and nanobots restored from my previous light fighter. My ship is supposed to have 0 capacity for either.

The autobuy module for bats and bots needs to check that the bats and bots each will not exceed the ship's capacity for each after they would be added, and if they do, only restore up to each's capacity specifically (cap minus current).

**Comment by erikroe** [comment]
Fixed by Auto Insurance refactoring.
