### ISSUE TITLE
Autoinsurance ammo re-buy often makes players exceed their cargo capacity

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#28]
After missions where you used ammo and picked up loot, especially on smaller fighters you will return to base with a filled cargo hold. When trying to undock in this state of negative cargo space remaining, Hook will kick you for "cheating". Players shouldn't run into that, so this needs to be handled in some way that also doesn't jeopardise the convenience of ammo re-buy.

Possible solutions: 
- Auto-selling ammo, then cargo, that isn't part of or exceeds the insurance-stored values. Possibly a message informing the player that this has been done (prevening frustration of their loot cargo being sold, since they'd have to buy it back before leaving base)
- A warning that you currently have overfilled cargo hold
- Preventing the player from undocking with overfilled cargo on the base itself instead of handling with a kick when done
- Only restocking ammo until the cargo capacity is not exceeded (not recommended)

**Comment by erikroe** [comment]
Fixed by Auto Insurance refactoring.
