### ISSUE TITLE
Required follow up fixes for new autoinsurance and bank systems

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#29]
* Insurance cost is not properly applied but still restores everything (across every insured equip?), regardless of whether the player does or does not have the money upon undocking.
** It is good if the insurance gives "priority" to insurance groups, e.g. when you undock with only the money to insure your mounted equip but not your ammo, it should always adapt what's currently insured and inform the player accordingly.

* The autoinsurance message is currently not correct, possibly related to the issue above where the insurance cost is not properly applied. It always says "autoinsurance is INACTIVE", whether on a base or in space.
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/assets/79576409/2e08e0e3-2deb-4713-8197-9623ef8cd815)

* As noted in https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/issues/27, switching ships while insurance is active will under circumstances restore things like bats&bots to invalid amounts. The fix suggested by Nekura is to disable and reenable the list of auto-insurance classes of the player automatically when buying a new ship.

* As noted in https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/issues/28, automatic ammo restoration when a player has picked up loot (different ammo, goods) out in space will easily push a players' cargo load to overfull. Undocking with overfull cargo results in a guaranteed kick by the anticheat. This needs a solution, ideally one that doesn't defeat the purpose of the convenience of the ammo resupply in the first place.

* Like the issue above, *sometimes* docking will also include the anti-cheat kick mid-restoration. This one seems incionsistent so I cannot nail down the cause precisely. It occured to me regularily when docking after missions with a Bloodhound I filled to the brim with mines and missiles when starting missions. Sometimes when returning to a base without clearing any foreign cargo space consuming items, it would kick me while docking, other times there would be nothing wrong. When being kicked, symptomatic was that my ammo was only partially restored (some ammo types were fully restocked, others were left in the state before docking). This kick might also permanently lose players their lost mounted equipment if it occurs while they have blown off items, but I have not confirmed this yet.

* Bank money overflows when a player's deposit reaches 2^31 credits. This needs some kind of catch to prevent long-time players from losing all their money.
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/assets/79576409/f1ce06ef-f1fa-416a-a578-06e74ea8cd42)

**Comment by erikroe** [comment]
Banking issue was fixed for now. Not the most fancy way, but it is.

**Comment by erikroe** [comment]
@Caenen is this still relevant or has everything been fixed?
