### ISSUE TITLE
Cloak crashes Client Computer completely on use

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR-Hook#31]
There's been at least two players with the problem of Cloak crashing their entire PC on activation on their ship. This is a severe bug that should be fixed immediately.

System Details of one of the affected players:
OS: Win 10 pro 64bit 
OS ver: 22H2
MOBO: B450M Bazooka V2
BIOS: P.B0 - AMD AGESA Combo-AM4 1.0.0.6
CPU: Ryzen 5 2600X
GPU: AMD Sapphire 5600xt 6gb
GPU DRIVER:  23.9.3
Ram: VENGEANCE® LPX 16GB (2 x 8GB) DDR4 DRAM 3000MHz C16 Memory Kit;
M2 drive: Kingston Snv2s1000g 1tb

More details in Discord Bug Ticket: https://discord.com/channels/672893425108123707/1163211623545176084

**Comment by Nekura** [comment]
We need Information about used AV-Software and installed AntiCheats too

**Comment by erikroe** [comment]
Solved by not using Cloak clienthook functionality any longer.
