### ISSUE TITLE
Autoinsurance fails to restore guns whose mount points are missing due to destroyed wings

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#34]
If the plugin believes an item on the insurance list cannot be mounted (due to the check saying that the hardpoint is not existing, or is not the right type etc) for correct or incorrect reasons, it should at least restore it into the player's cargo so they can re-equip it manually after repairing their wing or similar.

This may be directly or indirectly related to https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/issues/32 as well, more testing is needed. 

I'll volunteer to help resolve this if I'm given a little bit of assistence.

**Comment by erikroe** [comment]
Fixed by Auto-Insurance refactoring.
