### ISSUE TITLE
Autoinsurance fails to restore fixed-mounted equipment if balance check had failed

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#40]
For some reason I have encountered this bug again on the live server, despite thinking it was resolved. The only unusual circumstance at the time was that my insurance balance check had failed on undock due to being too short in money. I'm not running the latest server hook so I can't easily reproduce locally, so unless proven otherwise I'll assume that's the key cause.

![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/assets/79576409/b712c4ef-9567-41fd-ae33-cde43fb7b36d)

**Comment by erikroe** [comment]
Fixed along with another bug.
