### ISSUE TITLE
Asteroid Miner requires undock sequence created so the Docking plugin can work correctly

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#48]
Currently the live server has the configuration exchanged for the Liner.

If possible, the undock sequence needs to be added for the next update.

Otherwise, the config adjustment to use the liner needs to be configured in the repository so it persists in next update.

**Comment by erikroe** [comment]
Fixed via normal modding. The assigned model wasn't a station.
