### ISSUE TITLE
Custom client hook hotkeys stop working after escaping the chat window with ESC

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#50]
Repro:
1. verify cloak, dock, mark hotkeys work.
2. open chat
3. quit the chatbox with ESC (aborts message) rather than Enter (sends message)
4. Observe the hotkeys do not work anymore, until opening chat again and closing with Enter instead.

**Comment by erikroe** [comment]
The same bug happens whenever chat is also closed by using the F1 menu.

**Comment by erikroe** [comment]
Fixed
