### ISSUE TITLE
When your cloak activator is shot off, leaving and reentering the game in space does not uncloak you

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR-Hook#51]
Witnessed today during playtesting on the test server. Not sure if we forgot a check that removes or activates these when a player logs in, or we have a bug with said check.

Ship in question this happened on: Rh_Battleship

The safe file in question lived through the time we iterated cloak on the test server, so reproducing the bug before searching for it at least once may be advisable, in case it is caused by some leftover in the save game from that.

**Comment by erikroe** [comment]
Fixed for 2024.5.1
